# Generated by Django 4.0.5 on 2022-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoencoder', '0002_case_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='encoded',
            field=models.ImageField(null=True, upload_to='cases/encoded/%Y/%m/%d'),
        ),
    ]
